title: Anubhav Roy
description: Personal landing page and blog
plugins:
  - jekyll-feed
url: "https://justanubhav.github.io"   # your GitHub Pages domain
baseurl: ""      # the repo name, with a leading slash
markdown: kramdown
